import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { AppProvider } from '@/context/AppContext';
import Link from 'next/link';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AppProvider>
          <div className="min-h-screen flex flex-col">
            <header className="bg-primary-500 text-white shadow-md">
              <div className="container mx-auto px-4 py-4 flex justify-between items-center">
                <h1 className="text-xl font-bold">My App</h1>
                <nav className="space-x-4">
                  <Link href="/">Home</Link>
                  <Link href="/about">About</Link>
                  <Link href="/dashboard">Dashboard</Link>
                </nav>
              </div>
            </header>

            <main>{children}</main>

            <footer className="py-4 border-t border-gray-300 bg-gray-100">
              <div className="container mx-auto px-4 text-center">
                <p>&copy; {new Date().getFullYear()} My App. All rights reserved.</p>
              </div>
            </footer>
          </div>
        </AppProvider>
      </body>
    </html>
  );
}
