import type { Metadata } from 'next';
import { Geist, Geist_Mono, Montserrat } from 'next/font/google';
import './globals.css';
import { AppProvider } from '@/context/AppContext';
import LayoutWrapper from '@/components/LayoutWrapper/LayoutWrapper';
import { restaurantSchema } from '@/helpers/data';
import ApolloWrapper from './providers/ApolloWrapper';
import { Toaster } from 'sonner';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const fontMontserrat = Montserrat({
  variable: '--font-montserrat',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify(restaurantSchema),
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${fontMontserrat.variable} antialiased`}
      >
        <ApolloWrapper>
          <AppProvider>
            <div className="min-h-screen flex flex-col overflow-hidden">
              <LayoutWrapper>{children}</LayoutWrapper>
              <Toaster richColors />
            </div>
          </AppProvider>
        </ApolloWrapper>
      </body>
    </html>
  );
}
