import type { Metadata } from 'next';
import { Geist, Geist_Mono, Montserrat } from 'next/font/google';
import './globals.css';
import { AppProvider } from '@/context/AppContext';
import Footer from '@/components/Footer/Footer';
import Navbar from '@/components/Navbar/Navbar';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const fontMontserrat = Montserrat({
  variable: '--font-montserrat',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${fontMontserrat.variable} antialiased`}
      >
        <AppProvider>
          <div className="min-h-screen flex flex-col">
            <Navbar />

            <main>{children}</main>

            <Footer />
          </div>
        </AppProvider>
      </body>
    </html>
  );
}
